### ISSUE TITLE
ERROR While installing

### ISSUE THREAD

**Issue by blueedgetechno** [MarianDietz/atomforces#1]
> node-pty@0.9.0 install /tmp/apm-install-dir-120415-21077-1nofaug.s621/node_modules/atomforces/node_modules/node-pty
> node scripts/install.js

npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/usr/share/atom/resources/app/apm/bin/python-interceptor.sh" is v3.8.2, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:501:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:483:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:282:7)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:380:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:596:12)
gyp ERR! System Linux 5.2.0-2parrot1-amd64
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-120415-21077-1nofaug.s621/node_modules/atomforces/node_modules/node-pty
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
Aborted
Aborted
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/atomforces/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-120415-21077-1nofaug.s621/package.json'
npm WARN apm-install-dir-120415-21077-1nofaug.s621 No description
npm WARN apm-install-dir-120415-21077-1nofaug.s621 No repository field.
npm WARN apm-install-dir-120415-21077-1nofaug.s621 No README data
npm WARN apm-install-dir-120415-21077-1nofaug.s621 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! node-pty@0.9.0 install: `node scripts/install.js`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the node-pty@0.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/stuxnet/.atom/.apm/_logs/2020-05-15T18_29_57_531Z-debug.log

**Comment by blueedgetechno** [comment]
Parrot os
Latest version of python

**Comment by MarianDietz** [comment]
Sorry for the late reply.
If you are still interested in using this plugin, please try to install Python 2 instead of (or along with) Python 3.
node-gyp seems to depend on it.

**Comment by blueedgetechno** [comment]
Thanks, I will try it
